name: Publish
on:
  push:
    branches:
      - next
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node 12
      uses: actions/setup-node@v1
      with:
        node_version: 12.x
    - name: Write npmrc
      env:
        NPMRC: ${{ secrets.NPMRC }}
      run: echo "$NPMRC" > .npmrc
    - name: install
      run: yarn install  
    - name: Configure CI Git User
      run: |
        git remote rm origin
        git remote add origin "https://github-actions:$GITHUB_TOKEN@github.com/adobe/react-spectrum-v3.git"
        git fetch
        git config --global user.email octobot@github.com
        git config --global user.name GitHub Actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: deploy
      run: |
        git reset --hard
        git checkout next
        git reset --hard origin/next
        make ci
